version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: testboard
      POSTGRES_USER: testboard
      POSTGRES_PASSWORD: testboard
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testboard -d testboard"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
